using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using StudentManagementSystem.DTOs;
using StudentManagementSystem.Services;
using System.Security.Cryptography;
using System.Text;

namespace StudentManagementSystem.Controllers
{
    [ApiController]
        [Route("api/students")]
            [Authorize] // Protect all endpoints by default
                public class StudentsController : ControllerBase
                    {
                            private readonly IStudentService _studentService;
                                    private readonly AuthService _authService;

                                            public StudentsController(IStudentService studentService, AuthService authService)
                                                    {
                                                                _studentService = studentService;
                                                                            _authService = authService;
                                                                                    }

                                                                                            // ============================
                                                                                                    // ✅ REGISTER STUDENT
                                                                                                            // ============================
                                                                                                                    [AllowAnonymous]
                                                                                                                            [HttpPost("register")]
                                                                                                                                    public async Task<IActionResult> Register(RegisterStudentDto dto)
                                                                                                                                            {
                                                                                                                                                        var student = await _studentService.RegisterStudentAsync(dto);

                                                                                                                                                                    return Ok(new
                                                                                                                                                                                {
                                                                                                                                                                                                student.Id,
                                                                                                                                                                                                                student.FullName,
                                                                                                                                                                                                                                student.Email,
                                                                                                                                                                                                                                                student.CreatedAt
                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                            // ============================
                                                                                                                                                                                                                                                                                    // 🔑 LOGIN STUDENT
                                                                                                                                                                                                                                                                                            // ============================
                                                                                                                                                                                                                                                                                                    [AllowAnonymous]
                                                                                                                                                                                                                                                                                                            [HttpPost("login")]
                                                                                                                                                                                                                                                                                                                    public async Task<IActionResult> Login(LoginStudentDto dto)
                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                        var student = await _studentService.GetStudentByEmailAsync(dto.Email);

                                                                                                                                                                                                                                                                                                                                                    if (student == null || !VerifyPassword(dto.Password, student.PasswordHash))
                                                                                                                                                                                                                                                                                                                                                                    return Unauthorized("Invalid credentials");

                                                                                                                                                                                                                                                                                                                                                                                var token = _authService.GenerateJwtToken(student);

                                                                                                                                                                                                                                                                                                                                                                                            return Ok(new { token });
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                            // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                    // 🔐 PASSWORD VERIFICATION
                                                                                                                                                                                                                                                                                                                                                                                                                            // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                    private bool VerifyPassword(string input, string hash)
                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (string.IsNullOrEmpty(input) || string.IsNullOrEmpty(hash))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    using var sha256 = SHA256.Create();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(input));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var computedHash = Convert.ToBase64String(bytes);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return computedHash == hash;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // 🗑 DELETE STUDENT
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                [HttpDelete("{id}")]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public async Task<IActionResult> Delete(int id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var student = await _studentService.GetStudentByIdAsync(id);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (student == null)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return NotFound("Student not found");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await _studentService.DeleteStudentAsync(student);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Ok("Student deleted successfully");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }