using StudentManagementSystem.Data;          // Database context
using StudentManagementSystem.DTOs;          // DTOs (RegisterStudentDto)
using StudentManagementSystem.Models;        // Student entity model
using Microsoft.EntityFrameworkCore;         // EF Core async methods
using System.Security.Cryptography;          // SHA256 hashing
using System.Text;                           // Encoding

namespace StudentManagementSystem.Services
{
    // This class contains all business logic related to students
        public class StudentService : IStudentService
            {
                    private readonly AppDbContext _context;

                            // Constructor injection of DbContext
                                    public StudentService(AppDbContext context)
                                            {
                                                        _context = context;
                                                                }

                                                                        // ============================
                                                                                // Register a new student
                                                                                        // ============================
                                                                                                public async Task<Student> RegisterStudentAsync(RegisterStudentDto dto)
                                                                                                        {
                                                                                                                    // Check if email already exists to prevent duplicates
                                                                                                                                if (await _context.Students.AnyAsync(s => s.Email == dto.Email))
                                                                                                                                                throw new Exception("Email already registered");

                                                                                                                                                            // Create a new Student entity
                                                                                                                                                                        var student = new Student
                                                                                                                                                                                    {
                                                                                                                                                                                                    FullName = dto.FullName,
                                                                                                                                                                                                                    Email = dto.Email,
                                                                                                                                                                                                                                    PasswordHash = HashPassword(dto.Password),
                                                                                                                                                                                                                                                    CreatedAt = DateTime.UtcNow
                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                            // Add and save to database
                                                                                                                                                                                                                                                                                        _context.Students.Add(student);
                                                                                                                                                                                                                                                                                                    await _context.SaveChangesAsync();

                                                                                                                                                                                                                                                                                                                return student;
                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                // ============================
                                                                                                                                                                                                                                                                                                                                        // Get a student by email (used for login)
                                                                                                                                                                                                                                                                                                                                                // ============================
                                                                                                                                                                                                                                                                                                                                                        public async Task<Student?> GetStudentByEmailAsync(string email)
                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                            return await _context.Students.FirstOrDefaultAsync(s => s.Email == email);
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                            // ============================
                                                                                                                                                                                                                                                                                                                                                                                                    // Private password hashing method
                                                                                                                                                                                                                                                                                                                                                                                                            // ============================
                                                                                                                                                                                                                                                                                                                                                                                                                    private string HashPassword(string password)
                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                        using var sha256 = SHA256.Create();
                                                                                                                                                                                                                                                                                                                                                                                                                                                    var bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                return Convert.ToBase64String(bytes);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public async Task<Student?> GetStudentByIdAsync(int id)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return await _context.Students.FindAsync(id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            public async Task DeleteStudentAsync(Student student)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                _context.Students.Remove(student);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    await _context.SaveChangesAsync();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        public async Task<IEnumerable<Student>> GetAllStudentsAsync()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return await _context.Students.ToListAsync();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }